name: Deploy to MonsterASP.NET (Dev)

on:
  push:
    branches:
      - develope

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Publish Web API
      run: dotnet publish WadnereJwellors/WadnereJwellors.csproj --configuration Release --output ./publish

    - name: Deploy to MonsterASP.NET via WebDeploy
      uses: Azure/webapps-deploy@v3
      with:
        app-name: 'site97466'
        publish-profile: ${{ secrets.MONSTERASP_PUBLISH_PROFILE }}
        package: ./publish